// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

import './Richard.scss'
;

var ricardo1 = (require('./img/ricardo1.jpg'));

var ricardo2 = (require('./img/ricardo2.jpg'));

var ricardo3 = (require('./img/ricardo3.jpg'));

var ricardo4 = (require('./img/ricardo4.png'));

var ricardo5 = (require('./img/ricardo5.jpg'));

var milos = (require('./img/ricardo2.gif'));

var milos2 = (require('./img/ricardo3.gif'));

var milos3 = (require('./img/ricardo4.gif'));

var milos4 = (require('./img/ricardo5.gif'));

var milos5 = (require('./img/ricardo.gif'));

var head = (require('./img/head.png'));

function Richard(Props) {
  return React.createElement("div", {
              className: "richard"
            }, React.createElement("div", {
                  className: "images"
                }, React.createElement("img", {
                      src: ricardo1
                    }), React.createElement("img", {
                      src: ricardo2
                    }), React.createElement("img", {
                      src: ricardo3
                    }), React.createElement("img", {
                      src: ricardo4
                    }), React.createElement("img", {
                      src: ricardo5
                    })), React.createElement("div", {
                  className: "gifs"
                }, React.createElement("img", {
                      src: milos
                    }), React.createElement("img", {
                      src: milos2
                    }), React.createElement("img", {
                      src: milos3
                    }), React.createElement("img", {
                      src: milos4
                    }), React.createElement("img", {
                      src: milos5
                    })), React.createElement("div", {
                  className: "column one"
                }, React.createElement("img", {
                      src: head
                    }), React.createElement("img", {
                      src: head
                    }), React.createElement("img", {
                      src: head
                    })), React.createElement("div", {
                  className: "column two"
                }, React.createElement("img", {
                      src: head
                    }), React.createElement("img", {
                      src: head
                    }), React.createElement("img", {
                      src: head
                    })));
}

var make = Richard;

export {
  ricardo1 ,
  ricardo2 ,
  ricardo3 ,
  ricardo4 ,
  ricardo5 ,
  milos ,
  milos2 ,
  milos3 ,
  milos4 ,
  milos5 ,
  head ,
  make ,
  
}
/*  Not a pure module */
